---
deployment:
  tasks:
    - echo "---- Starting deployment ----"
    - export DEPLOYPATH=/home/mavoomva/portfolio.mavoid.com
    - cd $DEPLOYPATH
    - source ~/.nvm/nvm.sh
    - nvm use 20
    - npm install
    - npm run build
    - echo "✅ Build completed."
    - echo "---- Deployment finished ----"