export interface Project {
  id: string
  title: string
  description: string
  image: string
  category: string
  link: string
}

export const projects: Project[] = [
  {
    id: "1",
    title: "AI-Powered Analytics Dashboard",
    description: "A comprehensive analytics platform with AI-driven insights for business intelligence.",
    image: "/projects/project1.jpg",
    category: "web",
    link: "https://mavoid.com/projects/analytics-dashboard",
  },
  {
    id: "2",
    title: "Smart Home Automation System",
    description: "IoT-based home automation solution with mobile app control and voice integration.",
    image: "/projects/project2.jpg",
    category: "iot",
    link: "https://mavoid.com/projects/smart-home",
  },
  {
    id: "3",
    title: "Blockchain Supply Chain Tracking",
    description: "Transparent supply chain management system built on blockchain technology.",
    image: "/projects/project3.jpg",
    category: "blockchain",
    link: "https://mavoid.com/projects/supply-chain",
  },
  {
    id: "4",
    title: "Virtual Reality Training Platform",
    description: "Immersive VR training solution for industrial safety and operational procedures.",
    image: "/projects/project4.jpg",
    category: "vr",
    link: "https://mavoid.com/projects/vr-training",
  },
  {
    id: "5",
    title: "E-commerce Mobile Application",
    description: "Feature-rich mobile shopping experience with personalized recommendations.",
    image: "/projects/project5.jpg",
    category: "mobile",
    link: "https://mavoid.com/projects/ecommerce-app",
  },
  {
    id: "6",
    title: "Cloud Migration Strategy",
    description: "Enterprise-level cloud migration with zero downtime and enhanced security.",
    image: "/projects/project6.jpg",
    category: "cloud",
    link: "https://mavoid.com/projects/cloud-migration",
  },
  {
    id: "7",
    title: "Predictive Maintenance System",
    description: "ML-powered predictive maintenance for industrial equipment to prevent failures.",
    image: "/projects/project7.jpg",
    category: "ai",
    link: "https://mavoid.com/projects/predictive-maintenance",
  },
  {
    id: "8",
    title: "Cybersecurity Assessment Tool",
    description: "Comprehensive security assessment platform for identifying vulnerabilities.",
    image: "/projects/project8.jpg",
    category: "security",
    link: "https://mavoid.com/projects/security-assessment",
  },
  {
    id: "9",
    title: "Healthcare Patient Portal",
    description: "Secure patient portal for medical records access and appointment scheduling.",
    image: "/projects/project9.jpg",
    category: "web",
    link: "https://mavoid.com/projects/patient-portal",
  },
  {
    id: "10",
    title: "Augmented Reality Product Viewer",
    description: "AR application allowing customers to visualize products in their environment.",
    image: "/projects/project10.jpg",
    category: "ar",
    link: "https://mavoid.com/projects/ar-product-viewer",
  },
  {
    id: "11",
    title: "Financial Trading Platform",
    description: "Real-time trading platform with advanced analytics and automated strategies.",
    image: "/projects/project11.jpg",
    category: "web",
    link: "https://mavoid.com/projects/trading-platform",
  },
  {
    id: "12",
    title: "Smart City Infrastructure",
    description: "Connected urban infrastructure management with real-time monitoring and control.",
    image: "/projects/project12.jpg",
    category: "iot",
    link: "https://mavoid.com/projects/smart-city",
  },
  {
    id: "13",
    title: "Digital Identity Verification",
    description: "Secure and compliant identity verification system using biometric authentication.",
    image: "/projects/project13.jpg",
    category: "security",
    link: "https://mavoid.com/projects/identity-verification",
  },
  {
    id: "14",
    title: "Logistics Route Optimization",
    description: "AI-driven route optimization for logistics and delivery operations.",
    image: "/projects/project14.jpg",
    category: "ai",
    link: "https://mavoid.com/projects/route-optimization",
  },
  {
    id: "15",
    title: "Remote Team Collaboration Tool",
    description: "Comprehensive platform for remote teams to collaborate effectively.",
    image: "/projects/project15.jpg",
    category: "web",
    link: "https://mavoid.com/projects/collaboration-tool",
  },
  {
    id: "16",
    title: "Renewable Energy Monitoring",
    description: "IoT-based monitoring system for renewable energy installations.",
    image: "/projects/project16.jpg",
    category: "iot",
    link: "https://mavoid.com/projects/energy-monitoring",
  },
  {
    id: "17",
    title: "NFT Marketplace",
    description: "Secure and user-friendly marketplace for digital collectibles and NFTs.",
    image: "/projects/project17.jpg",
    category: "blockchain",
    link: "https://mavoid.com/projects/nft-marketplace",
  },
  {
    id: "18",
    title: "Telemedicine Platform",
    description: "HIPAA-compliant telemedicine solution for virtual healthcare consultations.",
    image: "/projects/project18.jpg",
    category: "web",
    link: "https://mavoid.com/projects/telemedicine",
  },
  {
    id: "19",
    title: "Autonomous Drone System",
    description: "AI-powered autonomous drone system for industrial inspections and monitoring.",
    image: "/projects/project19.jpg",
    category: "ai",
    link: "https://mavoid.com/projects/autonomous-drones",
  },
  {
    id: "20",
    title: "Educational Learning Platform",
    description: "Interactive e-learning platform with personalized learning paths.",
    image: "/projects/project20.jpg",
    category: "web",
    link: "https://mavoid.com/projects/learning-platform",
  },
]
